spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ???????????? school ???
    url: jdbc:mysql://localhost:3306/school?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: 2022122526
  jpa:
    hibernate:
      ddl-auto: none # ????????????????? JPA ????
    show-sql: true   # ????????? SQL ???????

server:
  port: 8080 # ?????????